test: add status report for test runner

diff --git a/run_test b/run_test
--- a/run_test
+++ b/run_test
@@ -1,16 +1,20 @@
 #!/usr/bin/env bash
 
+
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+NC='\033[0m'
+
 make lexer
 
 for cl in "$@"
 do 
     input_cl=../../examples/$cl
-    echo
-    echo
-    echo INPUT: $input_cl
-    echo --- actual 
-    echo +++ expected 
-    diff -u <(./lexer $input_cl) <(../../bin/lexer $input_cl)
-    echo END OF INPUT: $input_cl
-    echo No output means PASS
+    diff -u --color --label actual <(./lexer $input_cl) --label expected <(../../bin/lexer $input_cl)
+    if [[ "$?" -eq 0 ]]; then
+      printf "${GREEN}PASS${NC}\t"
+    else
+      printf "${RED}FAILED${NC}\t"
+    fi
+    printf "INPUT: ${input_cl}\n"
 done
